// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace BallBank.Specs.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TextingMembersFeature : object, global::Xunit.IClassFixture<TextingMembersFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Texting members", @"  A member chooses to be texted, at their own number, and when not to be. Consent is theirs alone:
  a treasurer cannot give it for them, and it belongs to the number, so a new number is not texted
  until the member opts in at it. Opted in, a member is texted what happens on their own account (dues
  assessed, a payment confirmed or rejected, an adjustment), and a treasurer is texted when a member says
  they paid. Nobody is texted about what they did themselves, nor inside their quiet hours; those texts
  wait until the hours end.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TextingMembers.feature"
#line hidden
        
        public TextingMembersFeature(TextingMembersFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 9
  #line hidden
#line 10
    await testRunner.GivenAsync("a league \"Holland Hogs\" with members Jacob, Sam, Priya", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/TextingMembers.feature.ndjson", 36);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A member opts in at their own number")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A member opts in at their own number")]
        public async global::System.Threading.Tasks.Task AMemberOptsInAtTheirOwnNumber()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A member opts in at their own number", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 12
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
    await testRunner.GivenAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
    await testRunner.WhenAsync("Sam opts in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
    await testRunner.ThenAsync("Sam is opted in to texts at \"+15550100002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A treasurer cannot opt a member in")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A treasurer cannot opt a member in")]
        public async global::System.Threading.Tasks.Task ATreasurerCannotOptAMemberIn()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A treasurer cannot opt a member in", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 17
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 18
    await testRunner.GivenAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 19
    await testRunner.WhenAsync("Jacob opts Sam in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
    await testRunner.ThenAsync("Jacob is not allowed to", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
    await testRunner.AndAsync("Sam is not opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A member cannot opt another member in")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A member cannot opt another member in")]
        public async global::System.Threading.Tasks.Task AMemberCannotOptAnotherMemberIn()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A member cannot opt another member in", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 24
    await testRunner.GivenAsync("Priya has recorded the phone number \"555 010 0003\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
    await testRunner.WhenAsync("Sam opts Priya in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
    await testRunner.ThenAsync("Sam is not allowed to", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 27
    await testRunner.AndAsync("Priya is not opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Consent needs a phone number on record")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "Consent needs a phone number on record")]
        public async global::System.Threading.Tasks.Task ConsentNeedsAPhoneNumberOnRecord()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Consent needs a phone number on record", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.WhenAsync("Sam opts in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
    await testRunner.ThenAsync("opting in is refused because \"Text messages go to a specific number. Add your pho" +
                        "ne number first.\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 32
    await testRunner.AndAsync("Sam is not opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A member withdraws consent")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A member withdraws consent")]
        public async global::System.Threading.Tasks.Task AMemberWithdrawsConsent()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A member withdraws consent", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 34
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 35
    await testRunner.GivenAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 36
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
    await testRunner.WhenAsync("Sam opts out of texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
    await testRunner.ThenAsync("Sam is not opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A new phone number is not texted until the member opts in at it")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A new phone number is not texted until the member opts in at it")]
        public async global::System.Threading.Tasks.Task ANewPhoneNumberIsNotTextedUntilTheMemberOptsInAtIt()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A new phone number is not texted until the member opts in at it", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 41
    await testRunner.GivenAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
    await testRunner.WhenAsync("Sam records the phone number \"555 010 0009\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
    await testRunner.ThenAsync("Sam is not opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
    await testRunner.WhenAsync("Sam opts in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
    await testRunner.ThenAsync("Sam is opted in to texts at \"+15550100009\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A treasurer changing a member\'s number takes their consent with it")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A treasurer changing a member\'s number takes their consent with it")]
        public async global::System.Threading.Tasks.Task ATreasurerChangingAMembersNumberTakesTheirConsentWithIt()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A treasurer changing a member\'s number takes their consent with it", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 48
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 49
    await testRunner.GivenAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
    await testRunner.WhenAsync("Jacob records the phone number \"555 010 0009\" for Sam", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
    await testRunner.ThenAsync("Sam is not opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Saving the same number again keeps consent")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "Saving the same number again keeps consent")]
        public async global::System.Threading.Tasks.Task SavingTheSameNumberAgainKeepsConsent()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Saving the same number again keeps consent", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 54
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 55
    await testRunner.GivenAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 56
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 57
    await testRunner.WhenAsync("Sam records the phone number \"(555) 010-0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 58
    await testRunner.ThenAsync("Sam is opted in to texts at \"+15550100002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Quiet hours are nine at night to nine in the morning Eastern until a member choos" +
            "es others")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "Quiet hours are nine at night to nine in the morning Eastern until a member choos" +
            "es others")]
        public async global::System.Threading.Tasks.Task QuietHoursAreNineAtNightToNineInTheMorningEasternUntilAMemberChoosesOthers()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Quiet hours are nine at night to nine in the morning Eastern until a member choos" +
                    "es others", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 60
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 61
    await testRunner.ThenAsync("Sam\'s quiet hours are 21 to 9 in \"America/New_York\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A member keeps their own quiet hours, on their own clock")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A member keeps their own quiet hours, on their own clock")]
        public async global::System.Threading.Tasks.Task AMemberKeepsTheirOwnQuietHoursOnTheirOwnClock()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A member keeps their own quiet hours, on their own clock", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 63
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 64
    await testRunner.WhenAsync("Sam sets their quiet hours from 22 to 7 in \"America/Chicago\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
    await testRunner.ThenAsync("Sam\'s quiet hours are 22 to 7 in \"America/Chicago\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Choosing quiet hours does not change whether a member is opted in")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "Choosing quiet hours does not change whether a member is opted in")]
        public async global::System.Threading.Tasks.Task ChoosingQuietHoursDoesNotChangeWhetherAMemberIsOptedIn()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Choosing quiet hours does not change whether a member is opted in", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 67
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 68
    await testRunner.GivenAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
    await testRunner.WhenAsync("Sam sets their quiet hours from 22 to 7 in \"America/Chicago\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
    await testRunner.ThenAsync("Sam is opted in to texts at \"+15550100002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Opening a season texts each opted-in member their dues, and nobody else")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "Opening a season texts each opted-in member their dues, and nobody else")]
        public async global::System.Threading.Tasks.Task OpeningASeasonTextsEachOpted_InMemberTheirDuesAndNobodyElse()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Opening a season texts each opted-in member their dues, and nobody else", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 73
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 74
    await testRunner.GivenAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 75
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
    await testRunner.WhenAsync("the treasurer opens the \"2026\" season with dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table30 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table30.AddRow(new string[] {
                            "BallBank: Holland Hogs assessed you $50.00 for Season dues, due Oct 1, 2026. Your" +
                                " statement: {Sam\'s statement}"});
#line 78
    await testRunner.ThenAsync("Sam was texted:", ((string)(null)), table30, "Then ");
#line hidden
#line 81
    await testRunner.AndAsync("Priya was not texted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="An assessment texts the member what it is for and when it is due")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "An assessment texts the member what it is for and when it is due")]
        public async global::System.Threading.Tasks.Task AnAssessmentTextsTheMemberWhatItIsForAndWhenItIsDue()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An assessment texts the member what it is for and when it is due", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 83
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 84
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 85
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 87
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
    await testRunner.WhenAsync("the treasurer assesses Sam $25 for \"Trophy fund\" due on 2026-11-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table31 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table31.AddRow(new string[] {
                            "BallBank: Holland Hogs assessed you $25.00 for Trophy fund, due Nov 1, 2026. Your" +
                                " statement: {Sam\'s statement}"});
#line 89
    await testRunner.ThenAsync("Sam was texted:", ((string)(null)), table31, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A treasurer is texted when a member says they paid")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A treasurer is texted when a member says they paid")]
        public async global::System.Threading.Tasks.Task ATreasurerIsTextedWhenAMemberSaysTheyPaid()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A treasurer is texted when a member says they paid", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 93
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 94
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 95
    await testRunner.AndAsync("Jacob has recorded the phone number \"555 010 0001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 96
    await testRunner.AndAsync("Jacob has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 97
    await testRunner.AndAsync("it is outside Jacob\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 98
    await testRunner.WhenAsync("Sam attests a $50 Venmo payment with reference \"VN-1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table32 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table32.AddRow(new string[] {
                            "BallBank: Sam says they paid $50.00 by Venmo (VN-1234) in Holland Hogs. Confirm o" +
                                "r reject it: {Sam\'s statement}"});
#line 99
    await testRunner.ThenAsync("Jacob was texted:", ((string)(null)), table32, "Then ");
#line hidden
#line 102
    await testRunner.AndAsync("Sam was not texted", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A member is texted when the treasurer confirms their payment")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A member is texted when the treasurer confirms their payment")]
        public async global::System.Threading.Tasks.Task AMemberIsTextedWhenTheTreasurerConfirmsTheirPayment()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A member is texted when the treasurer confirms their payment", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 104
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 105
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 106
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 107
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 108
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 109
    await testRunner.WhenAsync("Sam attests a $50 Venmo payment with reference \"VN-1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
    await testRunner.AndAsync("the treasurer confirms Sam\'s payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table33 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table33.AddRow(new string[] {
                            "BallBank: Holland Hogs confirmed your $50.00 Venmo payment. Your statement: {Sam\'" +
                                "s statement}"});
#line 111
    await testRunner.ThenAsync("Sam was texted:", ((string)(null)), table33, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A rejection carries its reason")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A rejection carries its reason")]
        public async global::System.Threading.Tasks.Task ARejectionCarriesItsReason()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A rejection carries its reason", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 115
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 116
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 117
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 118
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 120
    await testRunner.WhenAsync("Sam attests a $50 Zelle payment with reference \"ZL-0000\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 121
    await testRunner.AndAsync("the treasurer rejects Sam\'s payment because \"No Zelle with that reference arrived" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table34 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table34.AddRow(new string[] {
                            "BallBank: Holland Hogs rejected your $50.00 Zelle payment: No Zelle with that ref" +
                                "erence arrived. Your statement: {Sam\'s statement}"});
#line 122
    await testRunner.ThenAsync("Sam was texted:", ((string)(null)), table34, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="An adjustment carries its reason")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "An adjustment carries its reason")]
        public async global::System.Threading.Tasks.Task AnAdjustmentCarriesItsReason()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An adjustment carries its reason", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 126
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 127
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 128
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 131
    await testRunner.WhenAsync("the treasurer adjusts Sam\'s balance by -$5 because \"Waived: hosted the draft\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table35 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table35.AddRow(new string[] {
                            "BallBank: Holland Hogs lowered your balance by $5.00: Waived: hosted the draft. Y" +
                                "our statement: {Sam\'s statement}"});
#line 132
    await testRunner.ThenAsync("Sam was texted:", ((string)(null)), table35, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A treasurer is not texted about what they did themselves")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A treasurer is not texted about what they did themselves")]
        public async global::System.Threading.Tasks.Task ATreasurerIsNotTextedAboutWhatTheyDidThemselves()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A treasurer is not texted about what they did themselves", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 136
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 137
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 138
    await testRunner.AndAsync("Jacob has recorded the phone number \"555 010 0001\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 139
    await testRunner.AndAsync("Jacob has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 140
    await testRunner.AndAsync("it is outside Jacob\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
    await testRunner.WhenAsync("Jacob attests a $30 Cash payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 142
    await testRunner.AndAsync("the treasurer confirms Jacob\'s payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 143
    await testRunner.AndAsync("the treasurer adjusts Jacob\'s balance by -$5 because \"Waived: hosted the draft\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 144
    await testRunner.ThenAsync("Jacob was not texted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A member who did not opt in is not texted")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A member who did not opt in is not texted")]
        public async global::System.Threading.Tasks.Task AMemberWhoDidNotOptInIsNotTexted()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A member who did not opt in is not texted", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 146
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 147
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 148
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 149
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 150
    await testRunner.WhenAsync("Sam attests a $50 Zelle payment with reference \"ZL-0000\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 151
    await testRunner.AndAsync("the treasurer rejects Sam\'s payment because \"No Zelle with that reference arrived" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 152
    await testRunner.ThenAsync("Sam was not texted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A member who opts out is no longer texted")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A member who opts out is no longer texted")]
        public async global::System.Threading.Tasks.Task AMemberWhoOptsOutIsNoLongerTexted()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A member who opts out is no longer texted", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 154
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 155
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 156
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 157
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 158
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 159
    await testRunner.WhenAsync("Sam attests a $50 Zelle payment with reference \"ZL-0000\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 160
    await testRunner.AndAsync("Sam opts out of texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 161
    await testRunner.AndAsync("the treasurer rejects Sam\'s payment because \"No Zelle with that reference arrived" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 162
    await testRunner.ThenAsync("Sam was not texted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A member is not texted inside their quiet hours")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A member is not texted inside their quiet hours")]
        public async global::System.Threading.Tasks.Task AMemberIsNotTextedInsideTheirQuietHours()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A member is not texted inside their quiet hours", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 164
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 165
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 166
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 167
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 168
    await testRunner.AndAsync("it is inside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 169
    await testRunner.WhenAsync("Sam attests a $50 Zelle payment with reference \"ZL-0000\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 170
    await testRunner.AndAsync("the treasurer rejects Sam\'s payment because \"No Zelle with that reference arrived" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 171
    await testRunner.ThenAsync("Sam was not texted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A text held for a member\'s quiet hours arrives when they end")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A text held for a member\'s quiet hours arrives when they end")]
        public async global::System.Threading.Tasks.Task ATextHeldForAMembersQuietHoursArrivesWhenTheyEnd()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A text held for a member\'s quiet hours arrives when they end", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 173
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 174
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 175
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 176
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 177
    await testRunner.AndAsync("it is inside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 178
    await testRunner.WhenAsync("Sam attests a $50 Venmo payment with reference \"VN-1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 179
    await testRunner.AndAsync("the treasurer confirms Sam\'s payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 180
    await testRunner.AndAsync("the tick runs 1 hour later", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 181
    await testRunner.ThenAsync("Sam was not texted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 182
    await testRunner.WhenAsync("the tick runs 3 hours later", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
                global::Reqnroll.Table table36 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table36.AddRow(new string[] {
                            "BallBank: Holland Hogs confirmed your $50.00 Venmo payment. Your statement: {Sam\'" +
                                "s statement}"});
#line 183
    await testRunner.ThenAsync("Sam was texted:", ((string)(null)), table36, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Confirming a payment twice texts the member once")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "Confirming a payment twice texts the member once")]
        public async global::System.Threading.Tasks.Task ConfirmingAPaymentTwiceTextsTheMemberOnce()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Confirming a payment twice texts the member once", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 187
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 188
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 189
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0002\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 190
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 191
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 192
    await testRunner.WhenAsync("Sam attests a $50 Venmo payment with reference \"VN-1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 193
    await testRunner.AndAsync("the treasurer confirms Sam\'s payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 194
    await testRunner.AndAsync("the treasurer confirms Sam\'s payment", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table37 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table37.AddRow(new string[] {
                            "BallBank: Holland Hogs confirmed your $50.00 Venmo payment. Your statement: {Sam\'" +
                                "s statement}"});
#line 195
    await testRunner.ThenAsync("Sam was texted:", ((string)(null)), table37, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="The treasurer can tell a text that arrived from one that did not, and from one st" +
            "ill on its way")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "The treasurer can tell a text that arrived from one that did not, and from one st" +
            "ill on its way")]
        [global::Xunit.TraitAttribute("Category", "http")]
        [global::Xunit.InlineDataAttribute("queued", "sent", "23", new string[0])]
        [global::Xunit.InlineDataAttribute("sent", "sent", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("delivered", "delivered", "25", new string[0])]
        [global::Xunit.InlineDataAttribute("undelivered", "undelivered", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("failed", "failed", "27", new string[0])]
        public async global::System.Threading.Tasks.Task TheTreasurerCanTellATextThatArrivedFromOneThatDidNotAndFromOneStillOnItsWay(string reported, string shown, string @__pickleIndex, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "http"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("reported", reported);
            argumentsOfScenario.Add("shown", shown);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The treasurer can tell a text that arrived from one that did not, and from one st" +
                    "ill on its way", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 202
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 203
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 204
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0050\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 205
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 206
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 207
    await testRunner.WhenAsync("the treasurer assesses Sam $25 for \"Trophy fund\" due on 2026-11-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 208
    await testRunner.ThenAsync("Sam\'s text shows as sent", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 209
    await testRunner.WhenAsync(string.Format("Twilio reports Sam\'s text as \"{0}\"", reported), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 210
    await testRunner.ThenAsync(string.Format("Sam\'s text shows as {0}", shown), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A report made twice records one status")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A report made twice records one status")]
        [global::Xunit.TraitAttribute("Category", "http")]
        public async global::System.Threading.Tasks.Task AReportMadeTwiceRecordsOneStatus()
        {
            string[] tagsOfScenario = new string[] {
                    "http"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "28";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A report made twice records one status", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 221
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 222
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 223
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0050\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 224
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 225
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 226
    await testRunner.WhenAsync("the treasurer assesses Sam $25 for \"Trophy fund\" due on 2026-11-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 227
    await testRunner.AndAsync("Twilio reports Sam\'s text as \"delivered\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 228
    await testRunner.AndAsync("Twilio reports Sam\'s text as \"delivered\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 229
    await testRunner.ThenAsync("Twilio is answered that all is well", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 230
    await testRunner.AndAsync("Sam\'s text shows as delivered", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A report that arrives late does not take a status back")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A report that arrives late does not take a status back")]
        [global::Xunit.TraitAttribute("Category", "http")]
        public async global::System.Threading.Tasks.Task AReportThatArrivesLateDoesNotTakeAStatusBack()
        {
            string[] tagsOfScenario = new string[] {
                    "http"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "29";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A report that arrives late does not take a status back", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 233
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 234
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 235
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0050\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 236
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 237
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 238
    await testRunner.WhenAsync("the treasurer assesses Sam $25 for \"Trophy fund\" due on 2026-11-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 239
    await testRunner.AndAsync("Twilio reports Sam\'s text as \"delivered\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 240
    await testRunner.AndAsync("Twilio reports Sam\'s text as \"sent\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 241
    await testRunner.ThenAsync("Sam\'s text shows as delivered", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A report that Twilio did not sign is refused and changes nothing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A report that Twilio did not sign is refused and changes nothing")]
        [global::Xunit.TraitAttribute("Category", "http")]
        public async global::System.Threading.Tasks.Task AReportThatTwilioDidNotSignIsRefusedAndChangesNothing()
        {
            string[] tagsOfScenario = new string[] {
                    "http"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "30";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A report that Twilio did not sign is refused and changes nothing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 244
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 245
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 246
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0050\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 247
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 248
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 249
    await testRunner.WhenAsync("the treasurer assesses Sam $25 for \"Trophy fund\" due on 2026-11-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 250
    await testRunner.AndAsync("someone who is not Twilio reports Sam\'s text as \"delivered\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 251
    await testRunner.ThenAsync("the request is refused", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 252
    await testRunner.AndAsync("Sam\'s text shows as sent", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="STOP stops a number\'s texts in every league it is in, and START resumes them")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "STOP stops a number\'s texts in every league it is in, and START resumes them")]
        [global::Xunit.TraitAttribute("Category", "http")]
        public async global::System.Threading.Tasks.Task STOPStopsANumbersTextsInEveryLeagueItIsInAndSTARTResumesThem()
        {
            string[] tagsOfScenario = new string[] {
                    "http"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "31";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("STOP stops a number\'s texts in every league it is in, and START resumes them", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 255
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 256
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 257
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0052\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 258
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 259
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 260
    await testRunner.AndAsync("Sam is also in a second league at that number, opted in and outside their quiet h" +
                        "ours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 261
    await testRunner.WhenAsync("Sam replies \"STOP\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 262
    await testRunner.ThenAsync("Sam is opted out of texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 263
    await testRunner.WhenAsync("the treasurer assesses Sam $25 for \"Trophy fund\" due on 2026-11-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 264
    await testRunner.AndAsync("the second league\'s treasurer assesses Sam $25 for \"Trophy fund\" due on 2026-11-0" +
                        "1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 265
    await testRunner.ThenAsync("Sam was not texted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 266
    await testRunner.AndAsync("Sam was not texted in the second league", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 267
    await testRunner.WhenAsync("Sam replies \"START\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 268
    await testRunner.ThenAsync("Sam is not opted out of texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 269
    await testRunner.WhenAsync("the treasurer assesses Sam $10 for \"Banquet\" due on 2026-12-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 270
    await testRunner.AndAsync("the second league\'s treasurer assesses Sam $10 for \"Banquet\" due on 2026-12-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table38 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table38.AddRow(new string[] {
                            "BallBank: Holland Hogs assessed you $10.00 for Banquet, due Dec 1, 2026. Your sta" +
                                "tement: {Sam\'s statement}"});
#line 271
    await testRunner.ThenAsync("Sam was texted:", ((string)(null)), table38, "Then ");
#line hidden
#line 274
    await testRunner.AndAsync("Sam was texted once in the second league", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Any other reply leaves a number\'s texts as they were")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "Any other reply leaves a number\'s texts as they were")]
        [global::Xunit.TraitAttribute("Category", "http")]
        public async global::System.Threading.Tasks.Task AnyOtherReplyLeavesANumbersTextsAsTheyWere()
        {
            string[] tagsOfScenario = new string[] {
                    "http"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "32";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Any other reply leaves a number\'s texts as they were", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 277
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 278
    await testRunner.GivenAsync("season dues of $50 due on 2026-10-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 279
    await testRunner.AndAsync("Sam has recorded the phone number \"555 010 0053\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 280
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 281
    await testRunner.AndAsync("it is outside Sam\'s quiet hours", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 282
    await testRunner.WhenAsync("Sam replies \"Thanks!\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 283
    await testRunner.AndAsync("the treasurer assesses Sam $25 for \"Trophy fund\" due on 2026-11-01", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 284
    await testRunner.ThenAsync("Twilio is answered that all is well", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 285
    await testRunner.AndAsync("Sam is not opted out of texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table39 = new global::Reqnroll.Table(new string[] {
                            "message"});
                table39.AddRow(new string[] {
                            "BallBank: Holland Hogs assessed you $25.00 for Trophy fund, due Nov 1, 2026. Your" +
                                " statement: {Sam\'s statement}"});
#line 286
    await testRunner.AndAsync("Sam was texted:", ((string)(null)), table39, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A STOP that Twilio did not sign stops nobody\'s texts")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Texting members")]
        [global::Xunit.TraitAttribute("Description", "A STOP that Twilio did not sign stops nobody\'s texts")]
        [global::Xunit.TraitAttribute("Category", "http")]
        public async global::System.Threading.Tasks.Task ASTOPThatTwilioDidNotSignStopsNobodysTexts()
        {
            string[] tagsOfScenario = new string[] {
                    "http"};
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "33";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A STOP that Twilio did not sign stops nobody\'s texts", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 291
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
  await this.FeatureBackgroundAsync();
#line hidden
#line 292
    await testRunner.GivenAsync("Sam has recorded the phone number \"555 010 0054\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 293
    await testRunner.AndAsync("Sam has opted in to texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 294
    await testRunner.WhenAsync("someone who is not Twilio sends \"STOP\" from Sam\'s number", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 295
    await testRunner.ThenAsync("the request is refused", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 296
    await testRunner.AndAsync("Sam is not opted out of texts", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await TextingMembersFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await TextingMembersFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
